# Climate dataset EDA and cleaning

Landing page for the dataset: https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.ncdc:C00005

Documentation for the dataset: https://www.ncei.noaa.gov/pub/data/cirs/climdiv/county-readme.txt

In [1]:
import pandas as pd

In [2]:
cols = ['climate_division_code', 'jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']

We will start with the data for cooling degree days (CDD)

In [3]:
cdd = pd.read_csv(
    "../data/raw/climdiv-cddccy-v1.0.0-20260406.txt",
    sep=r'\s+',
    header=None,
    names=cols,
    dtype={"climate_division_code": str}, 
    
)

In [4]:
cdd

,climate_division_code,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec
0,01001261895,9.0,0.0,20.0,60.0,188.0,400.0,477.0,476.0,421.0,43.0,8.0,0.0
1,01001261896,9.0,7.0,14.0,151.0,365.0,391.0,518.0,562.0,386.0,86.0,21.0,5.0
2,01001261897,8.0,13.0,66.0,45.0,172.0,523.0,538.0,452.0,349.0,130.0,10.0,7.0
3,01001261898,23.0,0.0,52.0,15.0,313.0,494.0,491.0,441.0,336.0,50.0,0.0,0.0
4,01001261899,10.0,0.0,25.0,37.0,362.0,481.0,498.0,512.0,282.0,117.0,12.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
410119,48045262022,0.0,0.0,0.0,0.0,0.0,87.0,290.0,256.0,92.0,0.0,0.0,0.0
410120,48045262023,0.0,0.0,0.0,0.0,29.0,94.0,188.0,200.0,81.0,0.0,0.0,0.0
410121,48045262024,0.0,0.0,0.0,0.0,7.0,142.0,268.0,235.0,141.0,0.0,0.0,0.0
410122,48045262025,0.0,0.0,0.0,0.0,12.0,112.0,249.0,211.0,82.0,0.0,0.0,0.0
410123,48045262026,0.0,0.0,0.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0

In [5]:
# break up the division code into state, county, and year
cdd['noaa_state_code'] = cdd['climate_division_code'].str[:2] # state code is first 2 digits
cdd['county_3digit'] = cdd['climate_division_code'].str[2:5] # county code is next 3 digits
cdd['year'] = cdd['climate_division_code'].str[-4:] # year is last 4 digits

State codes 49 and 50 are missing. The data for Hawaii and Alaska were not recorded.

In [6]:
cdd['noaa_state_code'].unique()

array(['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11',
       '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33',
       '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44',
       '45', '46', '47', '48'], dtype=object)

In [7]:
# re-order the columns, remove climate_division_code
cdd = cdd[['noaa_state_code', 'county_3digit', 'year'] + list(cdd.columns)[1:-3]]

In [8]:
cdd

,noaa_state_code,county_3digit,year,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec
0,01,001,1895,9.0,0.0,20.0,60.0,188.0,400.0,477.0,476.0,421.0,43.0,8.0,0.0
1,01,001,1896,9.0,7.0,14.0,151.0,365.0,391.0,518.0,562.0,386.0,86.0,21.0,5.0
2,01,001,1897,8.0,13.0,66.0,45.0,172.0,523.0,538.0,452.0,349.0,130.0,10.0,7.0
3,01,001,1898,23.0,0.0,52.0,15.0,313.0,494.0,491.0,441.0,336.0,50.0,0.0,0.0
4,01,001,1899,10.0,0.0,25.0,37.0,362.0,481.0,498.0,512.0,282.0,117.0,12.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410119,48,045,2022,0.0,0.0,0.0,0.0,0.0,87.0,290.0,256.0,92.0,0.0,0.0,0.0
410120,48,045,2023,0.0,0.0,0.0,0.0,29.0,94.0,188.0,200.0,81.0,0.0,0.0,0.0
410121,48,045,2024,0.0,0.0,0.0,0.0,7.0,142.0,268.0,235.0,141.0,0.0,0.0,0.0
410122,48,045,2025,0.0,0.0,0.0,0.0,12.0,112.0,249.0,211.0,82.0,0.0,0.0,0.0
410123,48,045,2026,0.0,0.0,0.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0

In [9]:
# only want to observe 2024 since we are analyzing 2024 utility rates
cdd = cdd[cdd['year'] == '2024'].reset_index(drop=True)

No missing values in the data

In [10]:
cdd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3107 entries, 0 to 3106
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   noaa_state_code  3107 non-null   object
 1   county_3digit    3107 non-null   object
 2   year             3107 non-null   object
 3   jan              3107 non-null   float64
 4   feb              3107 non-null   float64
 5   mar              3107 non-null   float64
 6   apr              3107 non-null   float64
 7   may              3107 non-null   float64
 8   jun              3107 non-null   float64
 9   jul              3107 non-null   float64
 10  aug              3107 non-null   float64
 11  sep              3107 non-null   float64
 12  oct              3107 non-null   float64
 13  nov              3107 non-null   float64
 14  dec              3107 non-null   float64
dtypes: float64(12), object(3)
memory usage: 364.2+ KB

No outlier in the data - a max value of 1026 for July make sense as some areas are very hot. Minimum values of 0 make sense as some areas are cool all year round.

In [11]:
cdd.describe()

,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec
count,3107.000000,3107.000000,3107.000000,3107.000000,3107.000000,3107.000000,3107.000000,3107.000000,3107.000000,3107.000000,3107.000000,3107.000000
mean,3.108787,8.051818,20.995172,36.367557,150.510782,286.419054,360.267782,329.835533,190.919858,68.682008,19.540393,4.487609
std,12.140162,15.857124,35.801435,56.410099,130.122044,160.762657,152.670277,179.881492,126.370342,90.110846,44.429219,16.355085
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,45.000000,154.000000,237.000000,184.000000,99.000000,8.000000,0.000000,0.000000
50%,0.000000,0.000000,9.000000,12.000000,126.000000,288.000000,358.000000,310.000000,165.000000,30.000000,0.000000,0.000000
75%,0.000000,10.000000,26.000000,49.000000,221.500000,409.000000,488.000000,463.000000,274.000000,100.000000,13.000000,0.000000
max,184.000000,140.000000,313.000000,394.000000,707.000000,803.000000,1026.000000,951.000000,756.000000,515.000000,344.000000,199.000000

In [12]:
with open("../data/raw/climdiv-cddccy-v1.0.0-20260406.txt") as f:
    for line in f:
        if line.startswith("04025262024"):  # state 04, county 025, var 26, year 202x
            print(line)
            print(f"division code: {line[:11]}")
            print(f"state code: {line[:2]}")
            print(f"county FIPS code: {line[2:5]}")
            print(f"year: {line[7:11]}")

04025262024    17.    37.    79.   216.   479.   803.  1026.   951.   756.   515.    47.    29.

division code: 04025262024
state code: 04
county FIPS code: 025
year: 2024

In the dataset, the state code, which is the first two digits of climate_division_code, is determined by the alphabetical order of the two-letter state codes. However, actual FIPS codes use a different mapping of states to state codes. state_lookup will map the NOAA state code to the FIPS state code. This will allow us to merge this dataset with the election and utility datasets.

The mapping from the state codes used in the data to FIPS state codes can be viewed in the state code table in the documentation: https://www.ncei.noaa.gov/pub/data/cirs/climdiv/county-readme.txt

In [13]:
state_lookup = {
    "01": "01",  # AL
    "02": "04",  # AZ
    "03": "05",  # AR
    "04": "06",  # CA
    "05": "08",  # CO
    "06": "09",  # CT
    "07": "10",  # DE
    "08": "12",  # FL
    "09": "13",  # GA
    "10": "16",  # ID
    "11": "17",  # IL
    "12": "18",  # IN
    "13": "19",  # IA
    "14": "20",  # KS
    "15": "21",  # KY
    "16": "22",  # LA
    "17": "23",  # ME
    "18": "24",  # MD
    "19": "25",  # MA
    "20": "26",  # MI
    "21": "27",  # MN
    "22": "28",  # MS
    "23": "29",  # MO
    "24": "30",  # MT
    "25": "31",  # NE
    "26": "32",  # NV
    "27": "33",  # NH
    "28": "34",  # NJ
    "29": "35",  # NM
    "30": "36",  # NY
    "31": "37",  # NC
    "32": "38",  # ND
    "33": "39",  # OH
    "34": "40",  # OK
    "35": "41",  # OR
    "36": "42",  # PA
    "37": "44",  # RI
    "38": "45",  # SC
    "39": "46",  # SD
    "40": "47",  # TN
    "41": "48",  # TX
    "42": "49",  # UT
    "43": "50",  # VT
    "44": "51",  # VA
    "45": "53",  # WA
    "46": "54",  # WV
    "47": "55",  # WI
    "48": "56",  # WY
}

Map the NOAA state codes to FIPS state codes, then reconstruct the county FIPs code by appending the 3-digit county code to the state code

In [14]:
cdd['state_fips'] = cdd['noaa_state_code'].map(state_lookup)
cdd['county_fips'] = cdd['state_fips'] + cdd['county_3digit']

In [15]:
cdd

,noaa_state_code,county_3digit,year,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec,state_fips,county_fips
0,01,001,2024,9.0,16.0,39.0,72.0,312.0,450.0,544.0,527.0,350.0,127.0,59.0,8.0,01,01001
1,01,003,2024,21.0,32.0,69.0,122.0,395.0,501.0,580.0,592.0,415.0,192.0,116.0,20.0,01,01003
2,01,005,2024,15.0,19.0,51.0,76.0,293.0,453.0,542.0,534.0,326.0,132.0,78.0,7.0,01,01005
3,01,007,2024,7.0,14.0,36.0,59.0,290.0,418.0,502.0,484.0,313.0,122.0,43.0,6.0,01,01007
4,01,009,2024,0.0,11.0,29.0,44.0,248.0,399.0,465.0,450.0,279.0,93.0,22.0,0.0,01,01009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3102,48,037,2024,0.0,0.0,0.0,0.0,0.0,74.0,97.0,74.0,20.0,0.0,0.0,0.0,56,56037
3103,48,039,2024,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,56,56039
3104,48,041,2024,0.0,0.0,0.0,0.0,0.0,34.0,50.0,27.0,6.0,0.0,0.0,0.0,56,56041
3105,48,043,2024,0.0,0.0,0.0,0.0,0.0,100.0,188.0,137.0,75.0,0.0,0.0,0.0,56,56043
3106,48,045,2024,0.0,0.0,0.0,0.0,7.0,142.0,268.0,235.0,141.0,0.0,0.0,0.0,56,56045

Taking the sum of cooling degree days over the year will give an indicator of how much demand there is for heat in each county over the course of the year.

In [16]:
month_cols = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']

In [17]:
cdd['cdd_annual'] = cdd[month_cols].sum(axis=1)

In [18]:
cdd

,noaa_state_code,county_3digit,year,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec,state_fips,county_fips,cdd_annual
0,01,001,2024,9.0,16.0,39.0,72.0,312.0,450.0,544.0,527.0,350.0,127.0,59.0,8.0,01,01001,2513.0
1,01,003,2024,21.0,32.0,69.0,122.0,395.0,501.0,580.0,592.0,415.0,192.0,116.0,20.0,01,01003,3055.0
2,01,005,2024,15.0,19.0,51.0,76.0,293.0,453.0,542.0,534.0,326.0,132.0,78.0,7.0,01,01005,2526.0
3,01,007,2024,7.0,14.0,36.0,59.0,290.0,418.0,502.0,484.0,313.0,122.0,43.0,6.0,01,01007,2294.0
4,01,009,2024,0.0,11.0,29.0,44.0,248.0,399.0,465.0,450.0,279.0,93.0,22.0,0.0,01,01009,2040.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3102,48,037,2024,0.0,0.0,0.0,0.0,0.0,74.0,97.0,74.0,20.0,0.0,0.0,0.0,56,56037,265.0
3103,48,039,2024,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,56,56039,6.0
3104,48,041,2024,0.0,0.0,0.0,0.0,0.0,34.0,50.0,27.0,6.0,0.0,0.0,0.0,56,56041,117.0
3105,48,043,2024,0.0,0.0,0.0,0.0,0.0,100.0,188.0,137.0,75.0,0.0,0.0,0.0,56,56043,500.0
3106,48,045,2024,0.0,0.0,0.0,0.0,7.0,142.0,268.0,235.0,141.0,0.0,0.0,0.0,56,56045,793.0

In the end, just need the county code and the number of cooling degree days (CDDs)

In [19]:
cdd = cdd[['county_fips', 'cdd_annual']]

In [20]:
cdd

     county_fips  cdd_annual
0          01001      2513.0
1          01003      3055.0
2          01005      2526.0
3          01007      2294.0
4          01009      2040.0
...          ...         ...
3102       56037       265.0
3103       56039         6.0
3104       56041       117.0
3105       56043       500.0
3106       56045       793.0

[3107 rows x 2 columns]

We now have the total cooling degree days in 2024 for each county.

We will now use the function load_climdiv to perform the same operations to both the CDD and HDD files.

In [21]:
# returns a dataframe with columns county_fips and cdd/hdd_annual
def load_climdiv(path, year):
    cols = ['climate_division_code', 'jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']

    df = pd.read_csv(
        path,
        sep=r'\s+',
        header=None,
        names=cols,
        dtype={"climate_division_code": str}, 
    )

    # break up the division code into state, county, and year
    df['noaa_state_code'] = df['climate_division_code'].str[:2] # state code is first 2 digits
    df['county_3digit'] = df['climate_division_code'].str[2:5] # county code is next 3 digits
    df['year'] = df['climate_division_code'].str[-4:] # year is last 4 digits

    # re-order the columns, remove climate_division_code
    df = df[['noaa_state_code', 'county_3digit', 'year'] + list(df.columns)[1:-3]]

    # only want to observe year
    df = df[df['year'] == year].reset_index(drop=True)

    df['state_fips'] = df['noaa_state_code'].map(state_lookup)
    df['county_fips'] = df['state_fips'] + df['county_3digit']

    month_cols = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']

    name = "cdd_annual" if "cdd" in path else "hdd_annual"
    df[name] = df[month_cols].sum(axis=1).astype(int)
    df = df[['county_fips', name]]
    return df

In [22]:
cdd = load_climdiv("../data/raw/climdiv-cddccy-v1.0.0-20260406.txt", "2024")
hdd = load_climdiv("../data/raw/climdiv-hddccy-v1.0.0-20260406.txt", "2024")

In [23]:
cdd

     county_fips  cdd_annual
0          01001        2513
1          01003        3055
2          01005        2526
3          01007        2294
4          01009        2040
...          ...         ...
3102       56037         265
3103       56039           6
3104       56041         117
3105       56043         500
3106       56045         793

[3107 rows x 2 columns]

In [24]:
hdd

     county_fips  hdd_annual
0          01001        2003
1          01003        1355
2          01005        1811
3          01007        2212
4          01009        2544
...          ...         ...
3102       56037        7966
3103       56039       10282
3104       56041        8514
3105       56043        7017
3106       56045        6789

[3107 rows x 2 columns]

The combined data will now hold the number of cooling and heating degree days for each county in the year 202.

In [25]:
combined = pd.merge(cdd, hdd, on='county_fips', how='outer', validate='one_to_one')

In [26]:
combined

     county_fips  cdd_annual  hdd_annual
0          01001        2513        2003
1          01003        3055        1355
2          01005        2526        1811
3          01007        2294        2212
4          01009        2040        2544
...          ...         ...         ...
3102       56037         265        7966
3103       56039           6       10282
3104       56041         117        8514
3105       56043         500        7017
3106       56045         793        6789

[3107 rows x 3 columns]

In [27]:
combined.to_csv("../data/processed/climate_2024.csv", index=False)