# Election data EDA and cleaning

In [25]:
import pandas as pd

In [26]:
path = "../data/raw/countypres_2000-2024.csv"
elections = pd.read_csv(path, dtype={'county_fips': str})

In [27]:
elections.head()

,state,county_name,year,state_po,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
0,ALABAMA,AUTAUGA,2024,AL,1001,US PRESIDENT,OTHER,OTHER,293.0,28281,20260225,TOTAL
1,ALABAMA,AUTAUGA,2024,AL,1001,US PRESIDENT,CHASE OLIVER,LIBERTARIAN,65.0,28281,20260225,TOTAL
2,ALABAMA,AUTAUGA,2024,AL,1001,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,7439.0,28281,20260225,TOTAL
3,ALABAMA,AUTAUGA,2024,AL,1001,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,20484.0,28281,20260225,TOTAL
4,ALABAMA,BALDWIN,2024,AL,1003,US PRESIDENT,OTHER,OTHER,1276.0,122249,20260225,TOTAL

In [31]:
elections = [~elections['state'].isin(['ALASKA', 'HAWAII'])]

,state,county_name,year,state_po,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
0,ALABAMA,AUTAUGA,2024,AL,1001,US PRESIDENT,OTHER,OTHER,293.0,28281,20260225,TOTAL
1,ALABAMA,AUTAUGA,2024,AL,1001,US PRESIDENT,CHASE OLIVER,LIBERTARIAN,65.0,28281,20260225,TOTAL
2,ALABAMA,AUTAUGA,2024,AL,1001,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,7439.0,28281,20260225,TOTAL
3,ALABAMA,AUTAUGA,2024,AL,1001,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,20484.0,28281,20260225,TOTAL
4,ALABAMA,BALDWIN,2024,AL,1003,US PRESIDENT,OTHER,OTHER,1276.0,122249,20260225,TOTAL
...,...,...,...,...,...,...,...,...,...,...,...,...
94146,VERMONT,WINDSOR,2024,VT,50027,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,10458.0,34579,20260225,TOTAL
94147,VERMONT,WINDSOR,2024,VT,50027,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,22569.0,34579,20260225,TOTAL
94148,VERMONT,WINDSOR,2024,VT,50027,US PRESIDENT,OTHER,OTHER,1096.0,34579,20260225,TOTAL
94149,VERMONT,WINDSOR,2024,VT,50027,US PRESIDENT,SPOILED,NaN,16.0,34579,20260225,TOTAL
94150,VERMONT,WINDSOR,2024,VT,50027,US PRESIDENT,UNDERVOTES,NaN,274.0,34579,20260225,TOTAL

In [24]:
elections[elections['state'] == 'ALASKA']

,state,county_name,year,state_po,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
268,ALASKA,DISTRICT 01,2024,AK,02001,US PRESIDENT,CHASE OLIVER,LIBERTARIAN,73.0,8584,20260225,TOTAL
269,ALASKA,DISTRICT 01,2024,AK,02001,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,4861.0,8584,20260225,TOTAL
270,ALASKA,DISTRICT 01,2024,AK,02001,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,3367.0,8584,20260225,TOTAL
271,ALASKA,DISTRICT 01,2024,AK,02001,US PRESIDENT,OTHER,OTHER,283.0,8584,20260225,TOTAL
272,ALASKA,DISTRICT 02,2024,AK,02002,US PRESIDENT,CHASE OLIVER,LIBERTARIAN,75.0,9563,20260225,TOTAL
...,...,...,...,...,...,...,...,...,...,...,...,...
71427,ALASKA,DISTRICT 99,2020,AK,02099,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,59.0,433,20260225,TOTAL
71428,ALASKA,DISTRICT 99,2020,AK,02099,US PRESIDENT,JO JORGENSEN,LIBERTARIAN,1.0,433,20260225,TOTAL
71429,ALASKA,DISTRICT 99,2020,AK,02099,US PRESIDENT,JOSEPH R BIDEN JR,DEMOCRAT,373.0,433,20260225,TOTAL
71430,ALASKA,DISTRICT 99,2020,AK,02099,US PRESIDENT,OTHER,GREEN,0.0,433,20260225,TOTAL
71431,ALASKA,DISTRICT 99,2020,AK,02099,US PRESIDENT,OTHER,OTHER,0.0,433,20260225,TOTAL

In [4]:
elections[(elections['year'] == 2024) & (elections['state_po'] == 'WI') & (elections['county_fips'] == '55001')]

,state,county_name,year,state_po,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
20004,WISCONSIN,ADAMS,2024,WI,55001,US PRESIDENT,CHASE OLIVER,LIBERTARIAN,44.0,12882,20260225,NaN
20005,WISCONSIN,ADAMS,2024,WI,55001,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,7763.0,12882,20260225,NaN
20006,WISCONSIN,ADAMS,2024,WI,55001,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,4443.0,12882,20260225,NaN
20007,WISCONSIN,ADAMS,2024,WI,55001,US PRESIDENT,OTHER,OTHER,632.0,12882,20260225,NaN
20008,WISCONSIN,ADAMS,2024,WI,55001,US PRESIDENT,TOTAL VOTES CAST,NaN,12882.0,12882,20260225,NaN

In [5]:
# pad FIPS to 5 digits (restore leading zeros)
elections['county_fips'] = elections['county_fips'].str.zfill(5)

In [6]:
# filter data to just 2024 and the two major parties
e24 = elections[
    (elections['year'] == 2024) &
    (elections['party'].isin(['REPUBLICAN', 'DEMOCRAT']))
].copy()

In [7]:
e24

,state,county_name,year,state_po,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
2,ALABAMA,AUTAUGA,2024,AL,01001,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,7439.0,28281,20260225,TOTAL
3,ALABAMA,AUTAUGA,2024,AL,01001,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,20484.0,28281,20260225,TOTAL
5,ALABAMA,BALDWIN,2024,AL,01003,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,95798.0,122249,20260225,TOTAL
6,ALABAMA,BALDWIN,2024,AL,01003,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,24934.0,122249,20260225,TOTAL
8,ALABAMA,BARBOUR,2024,AL,01005,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,5606.0,9855,20260225,TOTAL
...,...,...,...,...,...,...,...,...,...,...,...,...
94135,VERMONT,WASHINGTON,2024,VT,50023,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,9327.0,35711,20260225,TOTAL
94139,VERMONT,WINDHAM,2024,VT,50025,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,6928.0,26085,20260225,TOTAL
94141,VERMONT,WINDHAM,2024,VT,50025,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,17904.0,26085,20260225,TOTAL
94146,VERMONT,WINDSOR,2024,VT,50027,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,10458.0,34579,20260225,TOTAL
94147,VERMONT,WINDSOR,2024,VT,50027,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,22569.0,34579,20260225,TOTAL

In [8]:
e24.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10372 entries, 2 to 94147
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   state           10372 non-null  object
 1   county_name     10372 non-null  object
 2   year            10372 non-null  int64
 3   state_po        10372 non-null  object
 4   county_fips     10372 non-null  object
 5   office          10372 non-null  object
 6   candidate       10372 non-null  object
 7   party           10372 non-null  object
 8   candidatevotes  10372 non-null  float64
 9   totalvotes      10372 non-null  int64
 10  version         10372 non-null  int64
 11  mode            9038 non-null   object
dtypes: float64(1), int64(3), object(8)
memory usage: 1.0+ MB

In [9]:
e24.describe()

          year  candidatevotes    totalvotes     version
count  10372.0    1.037200e+04  1.037200e+04     10372.0
mean    2024.0    1.718637e+04  4.701623e+04  20260225.0
std        0.0    5.848744e+04  1.230983e+05         0.0
min     2024.0    0.000000e+00  9.700000e+01  20260225.0
25%     2024.0    8.197500e+02  5.694000e+03  20260225.0
50%     2024.0    3.219500e+03  1.320600e+04  20260225.0
75%     2024.0    1.087325e+04  3.582900e+04  20260225.0
max     2024.0    2.417109e+06  3.728427e+06  20260225.0

In [10]:
# for each county: if TOTAL rows exist, keep only those rows
# otherwise, keep all rows
def resolve_county(group):
    if 'TOTAL' in group['mode'].values:
        return group[group['mode'] == 'TOTAL']
    return group

e24 = e24.groupby('county_fips', group_keys=False).apply(resolve_county)

/var/folders/by/8m6g8s3x5m30_ccy7fgy5xnc0000gn/T/ipykernel_5981/2365584827.py:8: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  e24 = e24.groupby('county_fips', group_keys=False).apply(resolve_county)

In [11]:
e24

,state,county_name,year,state_po,county_fips,office,candidate,party,candidatevotes,totalvotes,version,mode
2,ALABAMA,AUTAUGA,2024,AL,01001,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,7439.0,28281,20260225,TOTAL
3,ALABAMA,AUTAUGA,2024,AL,01001,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,20484.0,28281,20260225,TOTAL
5,ALABAMA,BALDWIN,2024,AL,01003,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,95798.0,122249,20260225,TOTAL
6,ALABAMA,BALDWIN,2024,AL,01003,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,24934.0,122249,20260225,TOTAL
8,ALABAMA,BARBOUR,2024,AL,01005,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,5606.0,9855,20260225,TOTAL
...,...,...,...,...,...,...,...,...,...,...,...,...
20486,WYOMING,UINTA,2024,WY,56041,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,1561.0,9089,20260225,NaN
20491,WYOMING,WASHAKIE,2024,WY,56043,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,3125.0,3877,20260225,NaN
20492,WYOMING,WASHAKIE,2024,WY,56043,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,656.0,3877,20260225,NaN
20497,WYOMING,WESTON,2024,WY,56045,US PRESIDENT,DONALD J TRUMP,REPUBLICAN,3069.0,3512,20260225,NaN
20498,WYOMING,WESTON,2024,WY,56045,US PRESIDENT,KAMALA D HARRIS,DEMOCRAT,378.0,3512,20260225,NaN

Fix known issues with county FIPS codes

In [12]:
# drop Kansas City, Missouri: reported separately from its 4 counties, can't cleanly join to utility/climate data
e24 = e24[e24['county_fips'] != '36000']

# Shannon County, SD was renamed to Oglala Lakota County in 2015
# its fips code was changed from  46113 to 46102
e24.loc[e24['county_fips'] == '46113', 'county_fips'] = '46102'

# drop Alaska: reports presidential returns by state house district, not by county, so won't align with other data
e24 = e24[e24['state'] != 'ALASKA']

# drop rows with missing FIPS
e24 = e24.dropna(subset=['county_fips'])

In [13]:
# pivot to wide format - one row per county
pivoted = e24.pivot_table(
    index=['county_fips', 'state', 'county_name'],
    columns='party',
    values='candidatevotes',
    aggfunc='sum' # only multiple rows if there is no row with TOTAL as the mode
).reset_index()

In [14]:
# attach total votes 
# max handles cases where totalvotes repeats across broken-out mode rows; sum would double-count)
totals = e24.groupby('county_fips')['totalvotes'].max().reset_index() # totalvotes is the same for all row for a county
pivoted = pivoted.merge(totals, on='county_fips')

In [15]:
totals

     county_fips  totalvotes
0          01001       28281
1          01003      122249
2          01005        9855
3          01007        9257
4          01009       28163
...          ...         ...
3107       56037       16698
3108       56039       13286
3109       56041        9089
3110       56043        3877
3111       56045        3512

[3112 rows x 2 columns]

In [16]:
# now has a totalvotes columns
pivoted

     county_fips    state county_name  DEMOCRAT  REPUBLICAN  totalvotes
0          01001  ALABAMA     AUTAUGA    7439.0     20484.0       28281
1          01003  ALABAMA     BALDWIN   24934.0     95798.0      122249
2          01005  ALABAMA     BARBOUR    4158.0      5606.0        9855
3          01007  ALABAMA        BIBB    1619.0      7572.0        9257
4          01009  ALABAMA      BLOUNT    2576.0     25354.0       28163
...          ...      ...         ...       ...         ...         ...
3107       56037  WYOMING  SWEETWATER    3731.0     12541.0       16698
3108       56039  WYOMING       TETON    8748.0      4134.0       13286
3109       56041  WYOMING       UINTA    1561.0      7282.0        9089
3110       56043  WYOMING    WASHAKIE     656.0      3125.0        3877
3111       56045  WYOMING      WESTON     378.0      3069.0        3512

[3112 rows x 6 columns]

In [17]:
# calculate each party's share of the vote
pivoted['rep_share'] = pivoted['REPUBLICAN'] / pivoted['totalvotes']
pivoted['dem_share'] = pivoted['DEMOCRAT']   / pivoted['totalvotes']
pivoted['rep_margin'] = pivoted['rep_share'] - pivoted['dem_share']

In [18]:
print(f"Final county count: {len(pivoted)}")
print(f"States covered: {pivoted['state'].nunique()}")
print("\nVote share summary:")
print(pivoted[['rep_share', 'dem_share', 'rep_margin']].describe())

Final county count: 3112
States covered: 50

Vote share summary:
         rep_share    dem_share   rep_margin
count  3112.000000  3112.000000  3112.000000
mean      0.668369     0.316476     0.351893
std       0.157738     0.154843     0.312473
min       0.064674     0.034965    -0.838069
25%       0.580458     0.195563     0.174376
50%       0.701534     0.282491     0.419546
75%       0.791468     0.404557     0.595251
max       0.959016     0.902743     0.921329

In [19]:
# flag any counties where major parties sum to >1 to check for potential double counting
suspect = pivoted[(pivoted['rep_share'] + pivoted['dem_share']) > 1.01]
if len(suspect) > 0:
    print(f"Warning: {len(suspect)} counties have rep+dem share > 1:")
    print(suspect[['state', 'county_name', 'rep_share', 'dem_share']])
else:
    print("\nAll counties have valid vote shares.")

All counties have valid vote shares.

In [20]:
pivoted.to_csv('../data/processed/elections_2024_county.csv', index=False)

In [23]:
pivoted['state'].unique()

array(['ALABAMA', 'ARIZONA', 'ARKANSAS', 'CALIFORNIA', 'COLORADO',
       'CONNECTICUT', 'DELAWARE', 'DISTRICT OF COLUMBIA', 'FLORIDA',
       'GEORGIA', 'HAWAII', 'IDAHO', 'ILLINOIS', 'INDIANA', 'IOWA',
       'KANSAS', 'KENTUCKY', 'LOUISIANA', 'MAINE', 'MARYLAND',
       'MASSACHUSETTS', 'MICHIGAN', 'MINNESOTA', 'MISSISSIPPI',
       'MISSOURI', 'MONTANA', 'NEBRASKA', 'NEVADA', 'NEW HAMPSHIRE',
       'NEW JERSEY', 'NEW MEXICO', 'NEW YORK', 'NORTH CAROLINA',
       'NORTH DAKOTA', 'OHIO', 'OKLAHOMA', 'OREGON', 'PENNSYLVANIA',
       'RHODE ISLAND', 'SOUTH CAROLINA', 'SOUTH DAKOTA', 'TENNESSEE',
       'TEXAS', 'UTAH', 'VERMONT', 'VIRGINIA', 'WASHINGTON',
       'WEST VIRGINIA', 'WISCONSIN', 'WYOMING'], dtype=object)