# Consumption data cleaning

Dataset: Table 5A - https://www.eia.gov/electricity/sales_revenue_price/

This dataset provides average monthly consumption (kWh) of electricity for each state. We will use this to predict monthly utility bills.

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("../data/raw/table_5A.xlsx")

In [3]:
df

,2024 Average Monthly Bill- Residential,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,"(Data from forms EIA-861- schedules 4A-D, EIA-...",NaN,NaN,NaN,NaN
1,State,Number of Customers,Average Monthly Consumption (kWh),Average Price (cents/kWh),Average Monthly Bill (Dollar and cents)
2,New England,6653781,601.47456,27.678886,166.48145
3,Connecticut,1552746,694.57073,28.745463,199.65757
4,Maine,742549,550.07503,24.286709,133.59512
...,...,...,...,...,...
59,Washington,3368978,955.45212,11.898243,113.68201
60,Pacific Noncontiguous,744909,528.27348,34.952982,184.64733
61,Alaska,298397,578.25481,24.822249,143.53585
62,Hawaii,446512,494.87173,42.863934,212.12149
63,U.S. Total,143144185,863.27502,16.479315,142.26181

In [4]:
df.columns = ['state', 'num_customers', 'avg_consumption', 'avg_price', 'avg_bill']

In [5]:
df

,state,num_customers,avg_consumption,avg_price,avg_bill
0,"(Data from forms EIA-861- schedules 4A-D, EIA-...",NaN,NaN,NaN,NaN
1,State,Number of Customers,Average Monthly Consumption (kWh),Average Price (cents/kWh),Average Monthly Bill (Dollar and cents)
2,New England,6653781,601.47456,27.678886,166.48145
3,Connecticut,1552746,694.57073,28.745463,199.65757
4,Maine,742549,550.07503,24.286709,133.59512
...,...,...,...,...,...
59,Washington,3368978,955.45212,11.898243,113.68201
60,Pacific Noncontiguous,744909,528.27348,34.952982,184.64733
61,Alaska,298397,578.25481,24.822249,143.53585
62,Hawaii,446512,494.87173,42.863934,212.12149
63,U.S. Total,143144185,863.27502,16.479315,142.26181

In [6]:
df.drop(index=[0, 1], inplace=True)

In [7]:
df

                    state num_customers avg_consumption  avg_price   avg_bill
2             New England       6653781       601.47456  27.678886  166.48145
3             Connecticut       1552746       694.57073  28.745463  199.65757
4                   Maine        742549       550.07503  24.286709  133.59512
5           Massachusetts       2924535       569.68131  29.349701  167.19976
6           New Hampshire        652608        618.9835  23.404467  144.86979
..                    ...           ...             ...        ...        ...
59             Washington       3368978       955.45212  11.898243  113.68201
60  Pacific Noncontiguous        744909       528.27348  34.952982  184.64733
61                 Alaska        298397       578.25481  24.822249  143.53585
62                 Hawaii        446512       494.87173  42.863934  212.12149
63             U.S. Total     143144185       863.27502  16.479315  142.26181

[62 rows x 5 columns]

In [8]:
df = df[['state', 'avg_consumption']]

In [9]:
df

                    state avg_consumption
2             New England       601.47456
3             Connecticut       694.57073
4                   Maine       550.07503
5           Massachusetts       569.68131
6           New Hampshire        618.9835
..                    ...             ...
59             Washington       955.45212
60  Pacific Noncontiguous       528.27348
61                 Alaska       578.25481
62                 Hawaii       494.87173
63             U.S. Total       863.27502

[62 rows x 2 columns]

In [10]:
df['state'].unique()

array(['New England', 'Connecticut', 'Maine', 'Massachusetts',
       'New Hampshire', 'Rhode Island', 'Vermont', 'Middle Atlantic',
       'New Jersey', 'New York', 'Pennsylvania', 'East North Central',
       'Illinois', 'Indiana', 'Michigan', 'Ohio', 'Wisconsin',
       'West North Central', 'Iowa', 'Kansas', 'Minnesota', 'Missouri',
       'Nebraska', 'North Dakota', 'South Dakota', 'South Atlantic',
       'Delaware', 'District of Columbia', 'Florida', 'Georgia',
       'Maryland', 'North Carolina', 'South Carolina', 'Virginia',
       'West Virginia', 'East South Central', 'Alabama', 'Kentucky',
       'Mississippi', 'Tennessee', 'West South Central', 'Arkansas',
       'Louisiana', 'Oklahoma', 'Texas', 'Mountain', 'Arizona',
       'Colorado', 'Idaho', 'Montana', 'Nevada', 'New Mexico', 'Utah',
       'Wyoming', 'Pacific Contiguous', 'California', 'Oregon',
       'Washington', 'Pacific Noncontiguous', 'Alaska', 'Hawaii',
       'U.S. Total'], dtype=object)

In [11]:
# drop Hawaii, Alaska, and regions
df = df[~df['state'].isin(['Hawaii', 'Alaska', 'New England', 'Middle Atlantic', 'South Atlantic', 'East North Central', 'West North Central', 'District of Columbia', 'West South Central', 'East South Central', 'Mountain', 'Pacific Contiguous', 'Pacific Noncontiguous', 'U.S. Total'])].reset_index(drop=True)

In [12]:
df['state'].unique()

array(['Connecticut', 'Maine', 'Massachusetts', 'New Hampshire',
       'Rhode Island', 'Vermont', 'New Jersey', 'New York',
       'Pennsylvania', 'Illinois', 'Indiana', 'Michigan', 'Ohio',
       'Wisconsin', 'Iowa', 'Kansas', 'Minnesota', 'Missouri', 'Nebraska',
       'North Dakota', 'South Dakota', 'Delaware', 'Florida', 'Georgia',
       'Maryland', 'North Carolina', 'South Carolina', 'Virginia',
       'West Virginia', 'Alabama', 'Kentucky', 'Mississippi', 'Tennessee',
       'Arkansas', 'Louisiana', 'Oklahoma', 'Texas', 'Arizona',
       'Colorado', 'Idaho', 'Montana', 'Nevada', 'New Mexico', 'Utah',
       'Wyoming', 'California', 'Oregon', 'Washington'], dtype=object)

Now have the contiguous United States

In [13]:
df['state'].nunique()

48

In [14]:
df

             state avg_consumption
0      Connecticut       694.57073
1            Maine       550.07503
2    Massachusetts       569.68131
3    New Hampshire        618.9835
4     Rhode Island       566.87211
5          Vermont       573.67036
6       New Jersey       662.38043
7         New York       571.15798
8     Pennsylvania       817.17369
9         Illinois       693.10633
10         Indiana        901.1318
11        Michigan       618.21319
12            Ohio       845.54097
13       Wisconsin       645.14576
14            Iowa       832.22151
15          Kansas        875.6638
16       Minnesota        712.2956
17        Missouri        1000.566
18        Nebraska       956.37673
19    North Dakota       1028.6311
20    South Dakota       993.75136
21        Delaware       910.66994
22         Florida        1104.135
23         Georgia       1074.0134
24        Maryland       928.83731
25  North Carolina       1015.3223
26  South Carolina       1050.4229
27        Virginia       1032.3587
28   West Virginia       1026.6441
29         Alabama       1143.1996
30        Kentucky       1046.5017
31     Mississippi       1155.8977
32       Tennessee       1153.5607
33        Arkansas       1048.3718
34       Louisiana       1201.8357
35        Oklahoma       1079.0596
36           Texas       1096.1478
37         Arizona       1074.9169
38        Colorado       674.22004
39           Idaho       943.80492
40         Montana        852.1579
41          Nevada       929.51129
42      New Mexico       654.09996
43            Utah       774.19085
44         Wyoming       863.38279
45      California        503.2089
46          Oregon       881.85305
47      Washington       955.45212

In [15]:
df = df.sort_values('state')

In [16]:
df

             state avg_consumption
29         Alabama       1143.1996
37         Arizona       1074.9169
33        Arkansas       1048.3718
45      California        503.2089
38        Colorado       674.22004
0      Connecticut       694.57073
21        Delaware       910.66994
22         Florida        1104.135
23         Georgia       1074.0134
39           Idaho       943.80492
9         Illinois       693.10633
10         Indiana        901.1318
14            Iowa       832.22151
15          Kansas        875.6638
30        Kentucky       1046.5017
34       Louisiana       1201.8357
1            Maine       550.07503
24        Maryland       928.83731
2    Massachusetts       569.68131
11        Michigan       618.21319
16       Minnesota        712.2956
31     Mississippi       1155.8977
17        Missouri        1000.566
40         Montana        852.1579
18        Nebraska       956.37673
41          Nevada       929.51129
3    New Hampshire        618.9835
6       New Jersey       662.38043
42      New Mexico       654.09996
7         New York       571.15798
25  North Carolina       1015.3223
19    North Dakota       1028.6311
12            Ohio       845.54097
35        Oklahoma       1079.0596
46          Oregon       881.85305
8     Pennsylvania       817.17369
4     Rhode Island       566.87211
26  South Carolina       1050.4229
20    South Dakota       993.75136
32       Tennessee       1153.5607
36           Texas       1096.1478
43            Utah       774.19085
5          Vermont       573.67036
27        Virginia       1032.3587
47      Washington       955.45212
28   West Virginia       1026.6441
13       Wisconsin       645.14576
44         Wyoming       863.38279

In [17]:
df.to_csv("../data/processed/consumption.csv", index=False)